#!/usr/bin/env ruby

require 'yaml'
require 'date'

POSTS_DIR = '_posts/'
CATEGORIES_DIR = 'categories/'

Dir.foreach(POSTS_DIR) do |post|

  next unless File.file?(POSTS_DIR + post) and post.end_with?('.md', '.markdown', '.html')
  # Parse only the front matter; Ruby 3.1+ YAML.load_file is safe_load and rejects dates
  frontMatter = File.read(POSTS_DIR + post)[/\A---\s*\n(.*?)\n---/m, 1]
  postYaml = YAML.safe_load(frontMatter.to_s, permitted_classes: [Date, Time]) || {}
  unless (postYaml['category'] == nil)
    category = postYaml['category'].to_s

    unless File.exist?(CATEGORIES_DIR + category.downcase + '.html')

      puts('[+] Generating #' + category + ' page')

      File.open(CATEGORIES_DIR + category.downcase + '.html', 'w') {|f| f.write(
      "---\nlayout: category\nsection-type: category\ntitle: " + category + "\n---\n## Category")}

    end

  end

end
